language: ruby
cache: bundler

rvm:
  - ruby
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - ben.lemasurier@gmail.com
    on_failure: change
    on_success: never
