language: ruby
cache: bundler

rvm:
  - ruby
  - 2.0.0

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - ben.lemasurier@gmail.com
    on_failure: change
    on_success: never
